// @flow
export const CART_ACTION_TYPES = {
    BUY_PRODUCTS_FAIL: "CART__BUY_PRODUCTS_FAIL",
    BUY_PRODUCTS_START: "CART__BUY_PRODUCTS_START",
    BUY_PRODUCTS_SUCCESS: "CART__BUY_PRODUCTS_SUCCESS",
    DECREMENT_PRODUCTS_COUNT: "CART__DECREMENT_PRODUCTS_COUNT",
    INCREMENT_PRODUCTS_COUNT: "CART__INCREMENT_PRODUCTS_COUNT",
    RESET_CART: "CART__RESET_CART",
};
