// @flow
export const ADMIN_ACTION_TYPES = {
    CREATE_PRODUCT_FAIL: "ADMIN__CREATE_PRODUCT_FAIL",
    CREATE_PRODUCT_START: "ADMIN__CREATE_PRODUCT_START",
    CREATE_PRODUCT_SUCCESS: "ADMIN__CREATE_PRODUCT_SUCCESS",
    GET_PURCHASES_FAIL: "ADMIN__GET_PURCHASES_FAIL",
    GET_PURCHASES_START: "ADMIN__GET_PURCHASES_START",
    GET_PURCHASES_SUCCESS: "ADMIN__GET_PURCHASES_SUCCESS",
};
