// @flow
export const AUTH_ACTION_TYPES = {
    LOGIN_FAIL: "AUTH__LOGIN_FAIL",
    LOGIN_START: "AUTH__LOGIN_START",
    LOGIN_SUCCESS: "AUTH__LOGIN_SUCCESS",
    LOGOUT: "AUTH__LOGOUT",
    SIGNUP_FAIL: "AUTH__SIGNUP_FAIL",
    SIGNUP_START: "AUTH__SIGNUP_START",
    SIGNUP_SUCCESS: "AUTH__SIGNUP_SUCCESS",
};
